---
title: Thoughts on AI
description: "Subjective and opinionated ruminations on AI and how I have been using it."
date: "17/08/2026"

---

Before I begin, let me say this clearly and unambiguously: I think the current hype around AI is a bubble, and it will burst probably within the year. I also think that many of the current 'tech leaders' of the AI industry are dishonest charlatans, who for purely selfish reasons push promises about an AI future that they don't believe in. And I believe that the AI hype-machine is doing active harm across to many communities, including independent artists, open source developers, and now, scientists. This being said, modern AI has proved itself quite useful and almost transformative in many use-cases. Although far from the all-powerful, all-knowing magical oracle that the hype-machine promises you, LLM-based AI has significant uses in quite a few applications. When bubbles burst and the hype circles subside, the current generation AI tools will remain and continue to be fine-tuned in these few limited domains, where this technology is genuinely useful.

With that out of the way, I would like to talk about few the applications domains that I found AI quite useful in my daily life as a researcher.

* For miscellaneous queries in daily life, I these days find chatbots more useful than usual Google search.
* As a tool for self-study and exploring new topics, I find AI tools quite valuable, as long as I do my due diligence and verify things. Google's NotebookLM deserves a special mention for this use-case. 
* For scientific literature search, AI tools are hit or miss. It can sometimes unearth useful literature that I would have otherwise missed, and the problem of hallucinating fake references has mostly been solved now. However, I find AI's ability to evaluate research the relevance and quality of research quite lacking.
* For applications like coding and writing, I find it most comfortable to use AI tools as a reference source instead of directly as a creator or editor. 
* I find AI tools within editors (text or code) extremely annoying. They get it the way and disrupt my thoughts all the time, so I don't use them that way.
* 'Vibe-coding' is a complete non-starter for me. As a researcher, I cannot afford to compromise on correctness; therefore I don't use code generated by AI, if ever, unless I understand it line-by-line. 
* Image and video generation are use-cases that do not usually feature in my daily life, therefore I haven't tried these extensively yet.

**Miscellaneous queries.** For simple daily life queries, I find AI chatbots quite useful, and often better than usual web search (partly due to Google becoming progressively worse over the past few years). Little everyday things that I would have looked up on Reddit or StackOverflow are easier to look ask a chatbot now. For applications involving medical or psychological advice, I advice extreme caution---I don't use them for this purpose. 

**Research.** This has been a mixed bag for me so far. On one hand, tools like NotebookLM are really good as tools for self-study. It does a very good job in summarising lectures, clarifying concepts etc. It also does a good job when I want a quick summary of a bunch of papers on a topic, as long as I am careful and double-check things later. For doing literature search, it is hit or miss: Gemini's 'Deep Research' mode does a good job in finding research papers and summarizing them. However, I find its ability to evaluate the quality of research somewhat lacking: the papers it finds varies quite widely on quality. It also seems to often miss important papers.

**Writing and copy-editing.** I have experimented with using AI for writing and copy-editing applications and immediately came to the conclusion that this is not an use-case that I like. I find the tone and style of most AI-writing quite bland, and I am very opinionated about how I write. Therefore, in most situations, I prefer to write my sentences myself the 'old-fashioned' way, without AI suggestions. For a while, I found AI to be quite useful in helping me write mundane emails. I used to overthink about every word and phrase in every email I write: having an LLM write an email for me took some of that stress away. However, once I got used to not stressing about 

**Coding.** I find LLM-based code assistants that live in your IDEs (GitHub Copilot and its ilk) extremely annoying. The experience of coding with an AI assitant is like coding with a talented but extremely enthusiastic intern looking over your shoulder and yelling suggestions at you every few minutes. The intern is talented and knows a lot of stuff, but he cannot read your mind, and is very new to the problem domains that you are working on: so the suggestions are rarely useful, and only gets in the way and slows you down. 

My preferred way of using AI for coding help is to have a chatbot open in a browser window on the side, and asking it specific questions when I need to. This is, for example, how I coded up this website. I have little to no experience in web-development, hence I extensively used a Gemini chat window on the side for reference and troubleshooting. This, plus [Quarto](https://quarto.org/docs/websites/) being extremely straightforward to work with, made the task so simple: a few years ago, when I first tried to create a github.io site, I got frustrated midway, gave up and moved to WordPress.

To wrap up, as a researcher, I find AI a useful tool in my daily life, as long as I am careful and judicious about how I use it. I believe that, like any piece of over-hyped technology, a healthy dose of skepticism and caution is warranted when you jump onboard. Over time, the excitement will die down and genuinely good use-cases will remain; while in the meantime, it is up to us to separate the grain from chaff.